server:
  port: 8088


spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qilong666/springcloud-config.git
          search-paths: /
          username: qilong666
          password: long931010
      label: master




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
