

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #datasource:
    #driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=Hongkong
    #url: jdbc:mysql://localhost:8066/TESTDB?useUnicode=true&characterEncoding=utf-8
    #username: root
    #password: root

mybatis:
  mapper-locations: mapper/*.xml


